//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class AbyssalBlessingInfoBean : BaseBean
{
	/// <summary>
	///图标名字
	/// </summary>
	public string icon_res;
	/// <summary>
	///父级深渊馈赠ID
	/// </summary>
	public long parent_id;
	/// <summary>
	///等级
	/// </summary>
	public int level;
	/// <summary>
	///buff_ids
	/// </summary>
	public string buff_ids;
	/// <summary>
	///名字-中文
	/// </summary>
	public long name;
	[JsonIgnore]
	public string name_language { get => _name_language.Get(() => TextHandler.Instance.GetTextById(AbyssalBlessingInfoCfg.fileName, name)); set => _name_language.Set(value); }
	private LanguageCache _name_language;
	/// <summary>
	///描述中文
	/// </summary>
	public long details;
	[JsonIgnore]
	public string details_language { get => _details_language.Get(() => TextHandler.Instance.GetTextById(AbyssalBlessingInfoCfg.fileName, details, 1)); set => _details_language.Set(value); }
	private LanguageCache _details_language;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
	/// <summary>
	///是否有效(0无效1有效)
	/// </summary>
	public int valid;
	/// <summary>
	///一局最多可获得次数(0=不限)
	/// </summary>
	public int max_count;
}
public partial class AbyssalBlessingInfoCfg : BaseCfg<long, AbyssalBlessingInfoBean>
{
	public static string fileName = "AbyssalBlessingInfo";
	protected static Dictionary<long, AbyssalBlessingInfoBean> dicData = null;
	public static Dictionary<long, AbyssalBlessingInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static AbyssalBlessingInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
			arrayData = System.Array.FindAll(arrayData, itemData => itemData.valid != 0);
		}
		return arrayData;
	}
	public static AbyssalBlessingInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			InitData(GetAllArrayData());
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(AbyssalBlessingInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, AbyssalBlessingInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			AbyssalBlessingInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
