//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class AttackModeExtInfoBean : BaseBean
{
	/// <summary>
	///攻击模块ID 对应AttackModeInfo
	/// </summary>
	public long attack_mode_id;
	/// <summary>
	///额外类型 1_Boss技能
	/// </summary>
	public int ext_type;
	/// <summary>
	///释放间隔（秒）
	/// </summary>
	public float trigger_interval;
	/// <summary>
	///触发场景(默认0): 0=攻击意图内释放(攻击循环出手点,trigger_interval生效); 1=释放技能意图(由NPC ai_param的skill_update事件全局周期驱动,走路也放,trigger_interval无效以ai_param为准)
	/// </summary>
	public int trigger_scene;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
}
public partial class AttackModeExtInfoCfg : BaseCfg<long, AttackModeExtInfoBean>
{
	public static string fileName = "AttackModeExtInfo";
	protected static Dictionary<long, AttackModeExtInfoBean> dicData = null;
	public static Dictionary<long, AttackModeExtInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static AttackModeExtInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static AttackModeExtInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			AttackModeExtInfoBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(AttackModeExtInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, AttackModeExtInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			AttackModeExtInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
