//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class AttackModeInfoBean : BaseBean
{
	/// <summary>
	///类引用
	/// </summary>
	public string class_name;
	/// <summary>
	///预制名字
	/// </summary>
	public string prefab_name;
	/// <summary>
	///视觉名字(DSP Instancing 批量渲染分桶key,空=不走批量渲染,与prefab_name独立)
	/// </summary>
	public string visual_name;
	/// <summary>
	///攻击buff（id:创建概率&id:创建概率）
	/// </summary>
	public string buff;
	/// <summary>
	///攻击搜索敌人类型（用于检测弹道是否打到）
	/// </summary>
	public int attack_search_type;
	/// <summary>
	///碰撞检测大小（用于点到点）
	/// </summary>
	public float collider_size;
	/// <summary>
	///碰撞范围搜索敌人类型（用于范围弹道检测）
	/// </summary>
	public int collider_area_type;
	/// <summary>
	///碰撞范围检测（用于范围）
	/// </summary>
	public string collider_area_size;
	/// <summary>
	///打击之后的特效(用&分隔)
	/// </summary>
	public string effect_hit;
	/// <summary>
	///受伤特效（默认不填，0为关闭）
	/// </summary>
	public string effect_damage;
	/// <summary>
	///移动速度
	/// </summary>
	public float speed_move;
	/// <summary>
	///音效-起始
	/// </summary>
	public long sound_start;
	/// <summary>
	///音效-miss
	/// </summary>
	public long sound_miss;
	/// <summary>
	///音效-击中
	/// </summary>
	public long sound_hit;
	/// <summary>
	///攻击起始位置偏移(x,y,z,空=0,叠加在生物攻击起始位置之上)
	/// </summary>
	public string start_pos_offset;
	/// <summary>
	///拖尾/残影参数(count:残影数&interval:采样间隔秒&startAlpha:最新档透明度&endAlpha:最老档透明度&color:染色rgb逗号分隔; 空=无拖尾; 残影=弹体贴图画在历史位置越老越透明; 需配合visual_name走DSP)
	/// </summary>
	public string trail_data;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
}
public partial class AttackModeInfoCfg : BaseCfg<long, AttackModeInfoBean>
{
	public static string fileName = "AttackModeInfo";
	protected static Dictionary<long, AttackModeInfoBean> dicData = null;
	public static Dictionary<long, AttackModeInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static AttackModeInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static AttackModeInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			AttackModeInfoBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(AttackModeInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, AttackModeInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			AttackModeInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
