//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class CreatureAttributeTypeInfoBean : BaseBean
{
	/// <summary>
	///标记名字
	/// </summary>
	public string mark_name;
	/// <summary>
	///资源名字
	/// </summary>
	public string res_name;
	/// <summary>
	///文本颜色
	/// </summary>
	public string color_text;
	/// <summary>
	///名字-中文
	/// </summary>
	public long name;
	[JsonIgnore]
	public string name_language { get => _name_language.Get(() => TextHandler.Instance.GetTextById(CreatureAttributeTypeInfoCfg.fileName, name)); set => _name_language.Set(value); }
	private LanguageCache _name_language;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
	/// <summary>
	/// Mod合并引用字段拼接（由Excel列头 [language]/[mode_id] 标记自动生成，请勿手改）：该行来自 Mod JsonText 时，下列字段按同一 modId 拼接，指向 Mod 自带配置/语言表的同自ID行；0=无引用不拼接
	/// </summary>
	public override void CombineModReferenceIds(int modId)
	{
		if (name > 0) name = CreatureAttributeTypeInfoCfg.CombineModId(modId, name);
	}
}
public partial class CreatureAttributeTypeInfoCfg : BaseCfg<long, CreatureAttributeTypeInfoBean>
{
	public static string fileName = "CreatureAttributeTypeInfo";
	protected static Dictionary<long, CreatureAttributeTypeInfoBean> dicData = null;
	public static Dictionary<long, CreatureAttributeTypeInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static CreatureAttributeTypeInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static CreatureAttributeTypeInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			CreatureAttributeTypeInfoBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(CreatureAttributeTypeInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, CreatureAttributeTypeInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			CreatureAttributeTypeInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
