//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class DoomCouncilRatingsInfoBean : BaseBean
{
	/// <summary>
	///图标名字
	/// </summary>
	public string icon_res;
	/// <summary>
	///投票票数
	/// </summary>
	public int vote;
	/// <summary>
	///名字
	/// </summary>
	public long name;
	[JsonIgnore]
	public string name_language { get => _name_language.Get(() => TextHandler.Instance.GetTextById(DoomCouncilRatingsInfoCfg.fileName, name)); set => _name_language.Set(value); }
	private LanguageCache _name_language;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
	/// <summary>
	/// Mod合并引用字段拼接（由Excel列头 [language]/[mode_id] 标记自动生成，请勿手改）：该行来自 Mod JsonText 时，下列字段按同一 modId 拼接，指向 Mod 自带配置/语言表的同自ID行；0=无引用不拼接
	/// </summary>
	public override void CombineModReferenceIds(int modId)
	{
		if (name > 0) name = DoomCouncilRatingsInfoCfg.CombineModId(modId, name);
	}
}
public partial class DoomCouncilRatingsInfoCfg : BaseCfg<long, DoomCouncilRatingsInfoBean>
{
	public static string fileName = "DoomCouncilRatingsInfo";
	protected static Dictionary<long, DoomCouncilRatingsInfoBean> dicData = null;
	public static Dictionary<long, DoomCouncilRatingsInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static DoomCouncilRatingsInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static DoomCouncilRatingsInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			DoomCouncilRatingsInfoBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(DoomCouncilRatingsInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, DoomCouncilRatingsInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			DoomCouncilRatingsInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
