//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class EquipSuitInfoBean : BaseBean
{
	/// <summary>
	///种族模组ID(0=通用)
	/// </summary>
	public long creature_model_id;
	/// <summary>
	///帽子道具ID(0=空)
	/// </summary>
	public long hat;
	/// <summary>
	///衣服道具ID(0=空)
	/// </summary>
	public long clothes;
	/// <summary>
	///裤子道具ID(0=空)
	/// </summary>
	public long pants;
	/// <summary>
	///鞋子道具ID(0=空)
	/// </summary>
	public long shoe;
	/// <summary>
	///鼻环道具ID(0=空)
	/// </summary>
	public long nose_ring;
	/// <summary>
	///戒指道具ID(0=空)
	/// </summary>
	public long finger_ring;
	/// <summary>
	///武器道具ID(0=空)
	/// </summary>
	public long weapon;
	/// <summary>
	///备注(套装名)
	/// </summary>
	public string remark;
}
public partial class EquipSuitInfoCfg : BaseCfg<long, EquipSuitInfoBean>
{
	public static string fileName = "EquipSuitInfo";
	protected static Dictionary<long, EquipSuitInfoBean> dicData = null;
	public static Dictionary<long, EquipSuitInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static EquipSuitInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static EquipSuitInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			EquipSuitInfoBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(EquipSuitInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, EquipSuitInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			EquipSuitInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
