//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class FightTypeInfiniteInfoBean : BaseBean
{
	/// <summary>
	///世界ID
	/// </summary>
	public long world_id;
	/// <summary>
	///难度等级(2~10, 无尽模式无难度1)
	/// </summary>
	public int level;
	/// <summary>
	///每轮强度倍率(每轮怪物HP/护甲/攻击力×该值^(轮-1), 含BOSS; 第1轮恒为1; 1=不递增)
	/// </summary>
	public float round_intensity_addrate;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
}
public partial class FightTypeInfiniteInfoCfg : BaseCfg<long, FightTypeInfiniteInfoBean>
{
	public static string fileName = "FightTypeInfiniteInfo";
	protected static Dictionary<long, FightTypeInfiniteInfoBean> dicData = null;
	public static Dictionary<long, FightTypeInfiniteInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static FightTypeInfiniteInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static FightTypeInfiniteInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			FightTypeInfiniteInfoBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(FightTypeInfiniteInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, FightTypeInfiniteInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			FightTypeInfiniteInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
