//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class FightTypeChallengeHundredInfoBean : BaseBean
{
	/// <summary>
	///进攻敌人列表(npcInfoId用,分割;每只怪独立随机,总量100)
	/// </summary>
	public string enemy_ids;
	/// <summary>
	///可抽中难度列表(用,分割;世界最高已解锁难度在列才可抽中本行)
	/// </summary>
	public string difficulty_levels;
	/// <summary>
	///挑战类型(0=普通挑战;1=BOSS挑战,通关宝箱奖励翻倍:装备件数x2/魔晶数量x2)
	/// </summary>
	public int challenge_type;
	/// <summary>
	///强度倍率(敌人HP/护甲/攻击力×该值;单值=全难度共用,或与难度列表等长的逗号分隔逐难度值;0或不配按1)
	/// </summary>
	public string attack_intensity_baserate;
	/// <summary>
	///进攻总时间(秒,100只怪在此时间内出完)
	/// </summary>
	public float attack_show_time;
	/// <summary>
	///道路数量(单个数x或范围x-y)
	/// </summary>
	public string road_num;
	/// <summary>
	///道路长度(单个数x或范围x-y)
	/// </summary>
	public string road_length;
	/// <summary>
	///战斗场景列表(用,分割;随机其一)
	/// </summary>
	public string fight_scene_ids;
	/// <summary>
	///击杀掉落魔晶(单值=全难度共用,或与难度列表等长的逗号分隔逐难度值)
	/// </summary>
	public string drop_crystal;
	/// <summary>
	///奖励-每箱魔晶(每档x或x-y;多档与难度列表等长的逗号分隔逐难度值)
	/// </summary>
	public string reward_crystal;
	/// <summary>
	///奖励-装备稀有度(单值=全难度共用,或与难度列表等长的逗号分隔逐难度值)
	/// </summary>
	public string reward_equip_rarity;
	/// <summary>
	///通关经验(阵容每只;单值=全难度共用,或与难度列表等长的逗号分隔逐难度值)
	/// </summary>
	public string reward_exp;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
}
public partial class FightTypeChallengeHundredInfoCfg : BaseCfg<long, FightTypeChallengeHundredInfoBean>
{
	public static string fileName = "FightTypeChallengeHundredInfo";
	protected static Dictionary<long, FightTypeChallengeHundredInfoBean> dicData = null;
	public static Dictionary<long, FightTypeChallengeHundredInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static FightTypeChallengeHundredInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static FightTypeChallengeHundredInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			FightTypeChallengeHundredInfoBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(FightTypeChallengeHundredInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, FightTypeChallengeHundredInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			FightTypeChallengeHundredInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
