//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class ItemsTypeBean : BaseBean
{
	/// <summary>
	///图标
	/// </summary>
	public string icon_res;
	/// <summary>
	///名字
	/// </summary>
	public long name;
	[JsonIgnore]
	public string name_language { get => _name_language.Get(() => TextHandler.Instance.GetTextById(ItemsTypeCfg.fileName, name)); set => _name_language.Set(value); }
	private LanguageCache _name_language;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
}
public partial class ItemsTypeCfg : BaseCfg<long, ItemsTypeBean>
{
	public static string fileName = "ItemsType";
	protected static Dictionary<long, ItemsTypeBean> dicData = null;
	public static Dictionary<long, ItemsTypeBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static ItemsTypeBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static ItemsTypeBean GetItemData(long key)
	{
		if (dicData == null)
		{
			ItemsTypeBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(ItemsTypeBean[] arrayData)
	{
		dicData = new Dictionary<long, ItemsTypeBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			ItemsTypeBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
