//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class NpcInfoBean : BaseBean
{
	/// <summary>
	///生物id
	/// </summary>
	public long creature_id;
	/// <summary>
	///NPC类型（0默认 1战斗 2议会固定 3议会随机）
	/// </summary>
	public int npc_type;
	/// <summary>
	///等级
	/// </summary>
	public int level;
	/// <summary>
	///生命值
	/// </summary>
	public float HP;
	/// <summary>
	///魔力
	/// </summary>
	public float MP;
	/// <summary>
	///护甲
	/// </summary>
	public float DR;
	/// <summary>
	///攻击力
	/// </summary>
	public float ATK;
	/// <summary>
	///攻击速度
	/// </summary>
	public float ASPD;
	/// <summary>
	///移动速度
	/// </summary>
	public float MSPD;
	/// <summary>
	///攻击搜索范围
	/// </summary>
	public float attack_search_range;
	/// <summary>
	///皮肤固定数据
	/// </summary>
	public string skin_data;
	/// <summary>
	///随机皮肤数据-CreatureRandomInfo
	/// </summary>
	public long creature_random_id;
	/// <summary>
	///装备道具Ids
	/// </summary>
	public string equip_item_ids;
	/// <summary>
	///随机装备（格式:装备池ID,稀有度1,稀有度2... 如 10000001,N,R；稀有度按RarityEnum枚举名，多个等概率抽、重复写加权；空=不随机）
	/// </summary>
	public string equip_random;
	/// <summary>
	///名字
	/// </summary>
	public long name;
	[JsonIgnore]
	public string name_language { get => _name_language.Get(() => TextHandler.Instance.GetTextById(NpcInfoCfg.fileName, name)); set => _name_language.Set(value); }
	private LanguageCache _name_language;
	/// <summary>
	///议会评级
	/// </summary>
	public int councilor_ratings;
	/// <summary>
	///称号数据
	/// </summary>
	public string title_data;
	/// <summary>
	///体型大小（空或0=默认1倍；"0.9,1.1"=区间随机；"1.1"=固定倍数；最终在目标大小基础上相乘）
	/// </summary>
	public string body_size;
	/// <summary>
	///Boss额外技能(AttackModeExtInfo的id,多个用,分隔)
	/// </summary>
	public string attack_mode_ext;
	/// <summary>
	///皮肤颜色数据（格式:部位类型int,r,g,b,a&... 如 3,255,255,255,255 表示Hair白色; rgba取0~255; 部位类型见CreatureSkinTypeEnum; 空=不固定颜色按创建时随机）
	/// </summary>
	public string skin_color_data;
	/// <summary>
	///地区限制（空=不限语言；填语言代码如 cn 或 cn,en 表示仅这些语言下出现，多个用英文逗号分隔；语言代码见LanguageEnum；目前仅终焉议会议员生成生效）
	/// </summary>
	public string region;
	/// <summary>
	///稀有度（空或0=N；按RarityEnum枚举值：1=N 2=R 3=SR 4=SSR 5=UR 6=L；配置后创建NPC生物时使用该稀有度）
	/// </summary>
	public int rarity;
	/// <summary>
	///头像图片-UI图集sprite名(支持「名,图集」后缀;空=用spine形象展示;无spine资源的NPC(如仅对话使用)配置此字段)
	/// </summary>
	public string icon_res;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
}
public partial class NpcInfoCfg : BaseCfg<long, NpcInfoBean>
{
	public static string fileName = "NpcInfo";
	protected static Dictionary<long, NpcInfoBean> dicData = null;
	public static Dictionary<long, NpcInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static NpcInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static NpcInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			NpcInfoBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(NpcInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, NpcInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			NpcInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
