//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class StoryInfoBean : BaseBean
{
	/// <summary>
	///故事名称
	/// </summary>
	public long name;
	[JsonIgnore]
	public string name_language { get => _name_language.Get(() => TextHandler.Instance.GetTextById(StoryInfoCfg.fileName, name)); set => _name_language.Set(value); }
	private LanguageCache _name_language;
	/// <summary>
	///触发类型(1引导 2剧情预留)
	/// </summary>
	public int trigger_type;
	/// <summary>
	///演出场景(1基地 2战斗 3议会)
	/// </summary>
	public int scene_type;
	/// <summary>
	///触发条件(1首次进基地后 2首次进战斗后 3战斗首次掉魔晶)
	/// </summary>
	public int trigger_condition;
	/// <summary>
	///同条件优先级(值小先播,默认0)
	/// </summary>
	public int priority;
	/// <summary>
	///是否只播一次(0可重复 1只一次)
	/// </summary>
	public int is_once;
	/// <summary>
	///是否有效(0无效)
	/// </summary>
	public int valid;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
}
public partial class StoryInfoCfg : BaseCfg<long, StoryInfoBean>
{
	public static string fileName = "StoryInfo";
	protected static Dictionary<long, StoryInfoBean> dicData = null;
	public static Dictionary<long, StoryInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static StoryInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
			arrayData = System.Array.FindAll(arrayData, itemData => itemData.valid != 0);
		}
		return arrayData;
	}
	public static StoryInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			InitData(GetAllArrayData());
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(StoryInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, StoryInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			StoryInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
