//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class StoryTalkInfoBean : BaseBean
{
	/// <summary>
	///所属故事ID(StoryInfo.id,编辑器按此过滤对话下拉)
	/// </summary>
	public long story_id;
	/// <summary>
	///说话NPC(NpcInfo.id,0=旁白无立绘无名字)
	/// </summary>
	public long npc_id;
	/// <summary>
	///对话内容
	/// </summary>
	public long content;
	[JsonIgnore]
	public string content_language { get => _content_language.Get(() => TextHandler.Instance.GetTextById(StoryTalkInfoCfg.fileName, content)); set => _content_language.Set(value); }
	private LanguageCache _content_language;
	/// <summary>
	///备注
	/// </summary>
	public string remark;
}
public partial class StoryTalkInfoCfg : BaseCfg<long, StoryTalkInfoBean>
{
	public static string fileName = "StoryTalkInfo";
	protected static Dictionary<long, StoryTalkInfoBean> dicData = null;
	public static Dictionary<long, StoryTalkInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static StoryTalkInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static StoryTalkInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			StoryTalkInfoBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(StoryTalkInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, StoryTalkInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			StoryTalkInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
