//------------------------------------------------------------------------------
// <auto-generated>
//     此文件由 ExcelEditorWindow 自动生成，请勿手动修改！
//     扩展方法/属性请写到同名的 *BeanPartial.cs 文件中。
//     AUTO-GENERATED-DO-NOT-EDIT
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
[Serializable]
public partial class StoryDetailsInfoBean : BaseBean
{
	/// <summary>
	///所属故事ID
	/// </summary>
	public long story_id;
	/// <summary>
	///步骤序号(升序执行)
	/// </summary>
	public int step_order;
	/// <summary>
	///步骤类型(1对话 2镜头移动 3等待 4特效 5音效 6淡入淡出)
	/// </summary>
	public int step_type;
	/// <summary>
	///执行方式(0阻塞等完成 1并发发起即下一步)
	/// </summary>
	public int is_async;
	/// <summary>
	///参数1(对话=对话ID,&分隔连播;镜头=目标标记self/core/portal/gashapon/juicer/altar/vat/achievement/council,back=回起始位;等待=秒;特效=特效ID;音效=音效ID;淡入淡出=out淡出/in淡入)
	/// </summary>
	public string param_1;
	/// <summary>
	///参数2(镜头=时长秒默认1;特效=目标标记空=核心/魔王位;淡入淡出=时长秒默认0.5)
	/// </summary>
	public string param_2;
	/// <summary>
	///参数2(对话=对话框对齐bottom/bottom_left/bottom_right/middle/middle_left/middle_right/top/top_left/top_right,空=bottom下对齐,可接|高亮目标demon魔王核心/crystal掉落魔晶/ui_fight_card手卡/ui_fight_remove删除按钮/ui_fight_att_progress进攻进度,可再接|形状rect方形默认/circle圆形|尺寸倍率默认1;镜头=时长秒默认1;特效=目标标记空=核心/魔王位;淡入淡出=时长秒默认0.5)
	/// </summary>
	public string param_3;
	/// <summary>
	///参数3(对话=偏移X默认0;镜头=缓动DOTween序号默认0;特效=尺寸倍率默认1)
	/// </summary>
	public string param_4;
	/// <summary>
	///参数4(对话=偏移Y默认0)
	/// </summary>
	public string remark;
}
public partial class StoryDetailsInfoCfg : BaseCfg<long, StoryDetailsInfoBean>
{
	public static string fileName = "StoryDetailsInfo";
	protected static Dictionary<long, StoryDetailsInfoBean> dicData = null;
	public static Dictionary<long, StoryDetailsInfoBean> GetAllData()
	{
		if (dicData == null)
		{
			var arrayData = GetAllArrayData();
			InitData(arrayData);
		}
		return dicData;
	}
	public static StoryDetailsInfoBean[] GetAllArrayData()
	{
		if (arrayData == null)
		{
			arrayData = GetInitData(fileName);
		}
		return arrayData;
	}
	public static StoryDetailsInfoBean GetItemData(long key)
	{
		if (dicData == null)
		{
			StoryDetailsInfoBean[] arrayData = GetInitData(fileName);
			InitData(arrayData);
		}
		return GetItemData(key, dicData);
	}
	public static void InitData(StoryDetailsInfoBean[] arrayData)
	{
		dicData = new Dictionary<long, StoryDetailsInfoBean>();
		for (int i = 0; i < arrayData.Length; i++)
		{
			StoryDetailsInfoBean itemData = arrayData[i];
			dicData.Add(itemData.id, itemData);
		}
	}
}
